name: ci
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-18.04
    env:
      GITHUB_EVENT_BEFORE: ${{ github.event.before }}
    steps:
    - run: |
        echo GITHUB_SHA=$GITHUB_SHA >> log.txt
        echo GITHUB_EVENT_BEFORE=$GITHUB_EVENT_BEFORE >> log.txt
        git add log.txt
        git commit -m "update log.txt"
        git push origin main

