name: ci
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-18.04
    env:
      GITHUB_EVENT_BEFORE: ${{ github.event.before }}
    steps:
    - run: |
        echo GITHUB_SHA=$GITHUB_SHA
        echo GITHUB_EVENT_BEFORE=$GITHUB_EVENT_BEFORE

